spring:
  application:
    name: coffee-flow-backend

  datasource:
    url: jdbc:mysql://localhost:3306/coffee_flow_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  server:
    port: 8080
    servlet:
      context-path: /api

# JWT Configuration
jwt:
  secret: mySecretKey12345678901234567890123456789012345678901234567890
  expiration: 86400000 # 24 hours in milliseconds

# Logging
logging:
  level:
    com.coffeeflow: DEBUG
    org.springframework.security: DEBUG
